- name: deploy to aws lambda
  lambda:
    name: "{{ lambda.name }}"
    state: present 
    zip_file: "{{ lambda.zip_file }}"
    runtime: 'go1.x'
    role: "{{ lambda.role }}"
    handler: "{{ lambda.name }}"
    environment_variables: "{{ lambda.env_vars }}"
    timeout: 3
